version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "07:00"
      timezone: "Europe/Amsterdam"
  - package-ecosystem: "npm"
    directory: "/frontend"
    cooldown:
      default-days: 5
    schedule:
      interval: "monthly"
      time: "07:00"
      timezone: "Europe/Amsterdam"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "07:00"
      timezone: "Europe/Amsterdam"
